name: ArgumentsCollector
version: 1.0
api-version: 1.13
main: cc.globalserver.ArgumentsCollector.Main
commands:
  ac:
    description: Interactive Command Implement
    usage: /<command> \"<cmd>\" <arguments prompts>
